images:
  source: tar
  tag: local
  pullPolicy: IfNotPresent

frontend:
  image:
    repository: k8s-ai-mcp-frontend

ingress:
  enabled: false

rbac:
  managedNamespaces:
    - dev
    - test

agentServer:
  replicas: 1
