apiVersion: v1
kind: Secret
metadata:
  name: k8s-ai-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  APP_ENCRYPTION_KEY: {{ .Values.backend.encryptionKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}
